let warriorprotection = [

    {   
        name: "Improved Bloodrage",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_racial_bloodrage.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "Increases the instant rage generated by your Bloodrage ability by 3.",
            2: "Increases the instant rage generated by your Bloodrage ability by 6."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Tactical Mastery",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_enchantarmor.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "You retain up to an additional 5 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance.",
            2: "You retain up to an additional 10 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance.",
            3: "You retain up to an additional 15 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Anticipation",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_mirrorimage.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "Increases your Defense skill by 4.",
            2: "Increases your Defense skill by 8.",
            3: "Increases your Defense skill by 12.",
            4: "Increases your Defense skill by 16.",
            5: "Increases your Defense skill by 20."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: true,
        lineNumber: 1,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 2,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shield Specialization",
        src: 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_06.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.",
            2: "Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs.",
            3: "Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs.",
            4: "Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs.",
            5: "Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Toughness",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_devotion.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Increases your armor value from items by 2%.",
            2: "Increases your armor value from items by 4%.",
            3: "Increases your armor value from items by 6%.",
            4: "Increases your armor value from items by 8%.",
            5: "Increases your armor value from items by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 2,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Last Stand",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_ashestoashes.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "When activated, this ability temporarily grants you 30% of your maximum hit points for 20 sec. After the effect expires, the hit points are lost."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Shield Block",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_defend.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Allows your Shield Block ability to block an additional attack, and increases the duration by 1 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Revenge",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_revenge.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Gives your Revenge ability a 15% chance to stun the target for 3 sec.",
            2: "Gives your Revenge ability a 30% chance to stun the target for 3 sec.",
            3: "Gives your Revenge ability a 4  5% chance to stun the target for 3 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Defiance",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_innerrage.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Increases the threat generated by your attacks by 5% while in Defensive Stance and increases your expertise by 2.",
            2: "Increases the threat generated by your attacks by 10% while in Defensive Stance and increases your expertise by 4.",
            3: "Increases the threat generated by your attacks by 15% while in Defensive Stance and increases your expertise by 6."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Sunder Armor",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_sunder.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Reduces the cost of your Sunder Armor and Devastate abilities by 1 rage point.",
            2: "Reduces the cost of your Sunder Armor and Devastate abilities by 2 rage point.",
            3: "Reduces the cost of your Sunder Armor and Devastate abilities by 3 rage point."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Disarm",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_disarm.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Increases the duration of your Disarm ability by 1 secs.",
            2: "Increases the duration of your Disarm ability by 2 secs.",
            3: "Increases the duration of your Disarm ability by 3 secs."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Taunt",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_reincarnation.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Reduces the cooldown of your Taunt ability by 1 sec.",
            2: "Reduces the cooldown of your Taunt ability by 2 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 4,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Shield Wall",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_shieldwall.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Increases the effect duration of your Shield Wall ability by 3 secs.",
            2: "Increases the effect duration of your Shield Wall ability by 5 secs."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Concussion Blow",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_thunderbolt.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Stuns the opponent for 5 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Shield Bash",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_shieldbash.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Gives your Shield Bash ability a 50% chance to silence the target for 3 sec.",
            2: "Gives your Shield Bash ability a 100% chance to silence the target for 3 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 5,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shield Mastery",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_shieldmastery.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 6,
        rankText: {
            1: "Increases the amount of damage absorbed by your shield by 10%.",
            2: "Increases the amount of damage absorbed by your shield by 20%.",
            3: "Increases the amount of damage absorbed by your shield by 30%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 6,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "One-Handed Weapon Specialization",
        src: 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_20.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 6,
        rankText: {
            1: "Increases the damage you deal with One-Handed Melee weapons by 2%.",
            2: "Increases the damage you deal with One-Handed Melee weapons by 4%.",
            3: "Increases the damage you deal with One-Handed Melee weapons by 6%.",
            4: "Increases the damage you deal with One-Handed Melee weapons by 8%.",
            5: "Increases the damage you deal with One-Handed Melee weapons by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 6,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Defensive State",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_defensivestance.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Reduces all spell damage taken while in Defensive Stance by 2%.",
            2: "Reduces all spell damage taken while in Defensive Stance by 4%.",
            3: "Reduces all spell damage taken while in Defensive Stance by 6%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shield Slam",
        src: 'https://wow.zamimg.com/images/wow/icons/large/inv_shield_05.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Slam the target with your shield, causing 420 to 440 damage, modified by your shield bloc value, and dispels 1 magic effect on the target. Also causes a high amount of threat."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Focused Rage",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_focusedrage.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Reduces the rage cost of your offensive abilities by 10.",
            2: "Reduces the rage cost of your offensive abilities by 20.",
            3: "Reduces the rage cost of your offensive abilities by 30."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 7,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Vitality",
        src: 'https://wow.zamimg.com/images/wow/icons/large/inv_helmet_21.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 8,
        rankText: {
            1: "Increases your total Stamina by 1% and your total Strength by 2%.",
            2: "Increases your total Stamina by 2% and your total Strength by 4%.",
            3: "Increases your total Stamina by 3% and your total Strength by 6%.",
            4: "Increases your total Stamina by 4% and your total Strength by 8%.",
            5: "Increases your total Stamina by 5% and your total Strength by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Devastate",
        src: 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_11.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 9,
        rankText: {
            1: "Sunder the target's armor causing the Sunder Armor effect. In addition, causes 50% of weapon damage plus 35 for each application of Sunder Armor on the target. The Sunder Armor effect can stack up to 5 times."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    }
]