let priestdiscipline = [

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: true,
        lineNumber: 1,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Unbreakable Will",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_magic_magearmor.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "Increases your chance to resist Stun, Fear, and Silence effects by an additional 3%.",
            2: "Increases your chance to resist Stun, Fear, and Silence effects by an additional 6%.",
            3: "Increases your chance to resist Stun, Fear, and Silence effects by an additional 9%.",
            4: "Increases your chance to resist Stun, Fear, and Silence effects by an additional 12%.",
            5: "Increases your chance to resist Stun, Fear, and Silence effects by an additional 15%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Wand Specialization",
        src: 'https://wow.zamimg.com/images/wow/icons/large/inv_wand_01.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "Increases your damage with Wands by 5%.",
            2: "Increases your damage with Wands by 10%.",
            3: "Increases your damage with Wands by 15%.",
            4: "Increases your damage with Wands by 20%.",
            5: "Increases your damage with Wands by 25%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: true,
        lineNumber: 1,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Silent Resolve",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_manaregentotem.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Reduces the threat generated by your Holy and Discipline spells by 4% and reduces the chance your spells will be dispelled by 4%.",
            2: "Reduces the threat generated by your Holy and Discipline spells by 8% and reduces the chance your spells will be dispelled by 8%.",
            3: "Reduces the threat generated by your Holy and Discipline spells by 12% and reduces the chance your spells will be dispelled by 12%.",
            4: "Reduces the threat generated by your Holy and Discipline spells by 16% and reduces the chance your spells will be dispelled by 16%.",
            5: "Reduces the threat generated by your Holy and Discipline spells by 20% and reduces the chance your spells will be dispelled by 20%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Power Word: Fortitude",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_wordfortitude.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 15%.",
            2: "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 30%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Power Word: Shield",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_powerwordshield.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Increases the damage absorbed by your Power Word: Shield by 5%.",
            2: "Increases the damage absorbed by your Power Word: Shield by 10%.",
            3: "Increases the damage absorbed by your Power Word: Shield by 15%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Martyrdom",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_tranquility.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Gives you a 50% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 10%.",
            2: "Gives you a 100% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 20%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Absolution",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_absolution.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 5%.",
            2: "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 10%.",
            3: "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 15%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Inner Focus",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_frost_windwalkon.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "When activated, reduces the Mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Meditation",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_sleep.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Allows 10% of your Mana regeneration to continue while casting.",
            2: "Allows 20% of your Mana regeneration to continue while casting.",
            3: "Allows 30% of your Mana regeneration to continue while casting."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 3,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Inner Fire",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_innerfire.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Increases the Armor bonus of your Inner Fire spell by 10%.",
            2: "Increases the Armor bonus of your Inner Fire spell by 20%.",
            3: "Increases the Armor bonus of your Inner Fire spell by 30%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Mental Agility",
        src: 'https://wow.zamimg.com/images/wow/icons/large/ability_hibernation.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Reduces the mana cost of your instant cast spells by 2%.",
            2: "Reduces the mana cost of your instant cast spells by 4%.",
            3: "Reduces the mana cost of your instant cast spells by 6%.",
            4: "Reduces the mana cost of your instant cast spells by 8%.",
            5: "Reduces the mana cost of your instant cast spells by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 4,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Mana Burn",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_manaburn.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Reduces the casting time of your Mana Burn spell by 0.5 sec.",
            2: "Reduces the casting time of your Mana Burn spell by 1.0 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 5,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Mental Strength",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_enchantarmor.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Increases your maximum Mana by 2%.",
            2: "Increases your maximum Mana by 4%.",
            3: "Increases your maximum Mana by 6%.",
            4: "Increases your maximum Mana by 8%.",
            5: "Increases your maximum Mana by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Divine Spirit",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_divinespirit.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Holy power infuses the target, incresing their Spirit by 17 for 30 min.",
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Divine Spirit",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_divinespirit.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Your Divine Spirit and Prayer of Spirit spells also increase the target's spell damage and healing by an amount equal to 5% of their total Spirit.",
            2: "Your Divine Spirit and Prayer of Spirit spells also increase the target's spell damage and healing by an amount equal to 10% of their total Spirit."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Focused Power",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_focusedpower.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 6,
        rankText: {
            1: "Your Smite, Mind Blast and Mass dispel spells have an additional 2% chance to hit.  In addition, your Mass Dispel cast time is reduced by 0.5 sec.",
            2: "Your Smite, Mind Blast and Mass dispel spells have an additional 4% chance to hit.  In addition, your Mass Dispel cast time is reduced by 1.0 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 6,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Force of Will",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_slowingtotem.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 6,
        rankText: {
            1: "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 1%.",
            2: "Increases your spell damage by 2% and the critical strike chance of your offensive spells by 2%.",
            3: "Increases your spell damage by 3% and the critical strike chance of your offensive spells by 3%.",
            4: "Increases your spell damage by 4% and the critical strike chance of your offensive spells by 4%.",
            5: "Increases your spell damage by 5% and the critical strike chance of your offensive spells by 5%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 6,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Focused Will",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_arcane_focusedpower.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "After taking a critical hit you gain the Focused Will effect, reducing all damage taken by 2% and increasing healing effects on you by 4%.  Stacks up to 3 times.  Lasts 8 sec.",
            2: "After taking a critical hit you gain the Focused Will effect, reducing all damage taken by 3% and increasing healing effects on you by 7%.  Stacks up to 3 times.  Lasts 8 sec.",
            3: "After taking a critical hit you gain the Focused Will effect, reducing all damage taken by 4% and increasing healing effects on you by 10%.  Stacks up to 3 times.  Lasts 8 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Power Infusion",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_powerinfusion.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Infuses the target with power, increasing spell casting speed by 20% and reducing the mana cost of all spells by 20%. Lasts 15 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Reflective Shield",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_powerwordshield.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Causes 10% of the damage absorbed by your Power Word: Shield to reflect back at the attacker. This damage causes no threat.",
            2: "Causes 10% of the damage absorbed by your Power Word: Shield to reflect back at the attacker. This damage causes no threat.",
            3: "Causes 10% of the damage absorbed by your Power Word: Shield to reflect back at the attacker. This damage causes no threat.",
            4: "Causes 10% of the damage absorbed by your Power Word: Shield to reflect back at the attacker. This damage causes no threat.",
            5: "Causes 10% of the damage absorbed by your Power Word: Shield to reflect back at the attacker. This damage causes no threat."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 7,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Enlightenment",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_arcane_mindmastery.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 8,
        rankText: {
            1: "Increases your total Stamina, Intellect and Spirit by 1%.",
            2: "Increases your total Stamina, Intellect and Spirit by 2%.",
            3: "Increases your total Stamina, Intellect and Spirit by 3%.",
            4: "Increases your total Stamina, Intellect and Spirit by 4%.",
            5: "Increases your total Stamina, Intellect and Spirit by 5%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Pain Suppression",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_painsupression.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 9,
        rankText: {
            1: "Instantly reduces a friendly target's threat by 5%, reduces all damage taken by 40% and increases resistance to dispel mechanics by 65% for 8 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    }
]