let priestshadow = [

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: true,
        lineNumber: 1,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Spirit Tap",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_requiem.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "Gives you a 20% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.",
            2: "Gives you a 40% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.",
            3: "Gives you a 60% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.",
            4: "Gives you a 80% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.",
            5: "Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Blackout",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_gathershadows.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: true,
        lineNumber: 1,
        rankText: {
            1: "Gives your Shadow damage spells a 2% chance to stun the target for 3 sec.",
            2: "Gives your Shadow damage spells a 4% chance to stun the target for 3 sec.",
            3: "Gives your Shadow damage spells a 6% chance to stun the target for 3 sec.",
            4: "Gives your Shadow damage spells a 8% chance to stun the target for 3 sec.",
            4: "Gives your Shadow damage spells a 10% chance to stun the target for 3 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: true,
        lineNumber: 1,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadow Affinity",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_shadowward.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Reduces the threat generated by your Shadow spells by 8%.",
            2: "Reduces the threat generated by your Shadow spells by 16%.",
            3: "Reduces the threat generated by your Shadow spells by 25%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Shadow Word: Pain",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_shadowwordpain.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Increases the duration of your Shadow Word: Pain spell by 3 sec.",
            2: "Increases the duration of your Shadow Word: Pain spell by 6 sec.",
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadow Focus",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_burningspirit.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 2,
        rankText: {
            1: "Reduces your target's chance to resist your Shadow spells by 2%.",
            2: "Reduces your target's chance to resist your Shadow spells by 4%.",
            3: "Reduces your target's chance to resist your Shadow spells by 6%.",
            4: "Reduces your target's chance to resist your Shadow spells by 8%.",
            5: "Reduces your target's chance to resist your Shadow spells by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 2,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Psychic Scream",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_psychicscream.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Reduces the cooldown of your Psychic Scream spell by 2 sec.",
            2: "Reduces the cooldown of your Psychic Scream spell by 4 sec.",
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Mind Blast",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_unholyfrenzy.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Reduces the cooldown of your Mind Blast spell by 0.5 sec.",
            2: "Reduces the cooldown of your Mind Blast spell by 1.0 sec.",
            3: "Reduces the cooldown of your Mind Blast spell by 1.5 sec.",
            4: "Reduces the cooldown of your Mind Blast spell by 2.0 sec.",
            5: "Reduces the cooldown of your Mind Blast spell by 2.5 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Mind Flay",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_siphonmana.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 3,
        rankText: {
            1: "Assault the target's mind with Shadow energy, causing 528 damage over 3 sec and slowing the target to 50% of their movement speed."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 3,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 4,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Fade",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_magic_lesserinvisibilty.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Decreases the cooldown of your Fade ability by 3 sec.",
            2: "Decreases the cooldown of your Fade ability by 6 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadow Reach",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_chilltouch.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Increases the range of your offensive Shadow spells by 10%.",
            2: "Increases the range of your offensive Shadow spells by 20%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadow Weaving",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_blackplague.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 4,
        rankText: {
            1: "Your Shadow damage spells have a 20% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec. Stacks up to 5 times.",
            2: "Your Shadow damage spells have a 40% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec. Stacks up to 5 times.",
            3: "Your Shadow damage spells have a 60% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec. Stacks up to 5 times.",
            4: "Your Shadow damage spells have a 80% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec. Stacks up to 5 times.",
            5: "Your Shadow damage spells have a 100% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec. Stacks up to 5 times."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Silence",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_impphaseshift.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Silences the target, preventing them from casting spells for 5 sec."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Vampiric Embrace",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_unsummonbuilding.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Afflicts your target with Shadow energy that causes all party members to be healed for 15% of any Shadow damage you deal for 1 min."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Improved Vampiric Embrace",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_improvedvampiricembrace.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Increases the percentage healed by Vampiric Embrace by an additional 5%.",
            2: "Increases the percentage healed by Vampiric Embrace by an additional 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Focused Mind",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_focusedmind.jpg',
        pointSpent: 0,
        pointLimit: 3,
        isEnable: false,
        lineNumber: 5,
        rankText: {
            1: "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by 5%.",
            2: "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by 10%.",
            3: "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by 15%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadow Resilience",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_grimward.jpg',
        pointSpent: 0,
        pointLimit: 2,
        isEnable: false,
        lineNumber: 6,
        rankText: {
            1: "Reduces the chance you'll be critically hit by all spells by 2%.",
            2: "Reduces the chance you'll be critically hit by all spells by 4%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 6,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Darkness",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_twilight.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 6,
        rankText: {
            1: "Increases your Shadow spell damage by 2%.",
            2: "Increases your Shadow spell damage by 4%.",
            3: "Increases your Shadow spell damage by 6%.",
            4: "Increases your Shadow spell damage by 8%.",
            5: "Increases your Shadow spell damage by 10%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 6,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 7,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadowform",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_shadowform.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%. However, you may not cast Holy spells while in this form."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Shadow Power",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_shadowpower.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 7,
        rankText: {
            1: "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 3%.",
            2: "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 6%.",
            3: "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 9%.",
            4: "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 12%.",
            5: "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 15%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 7,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Misery",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_misery.jpg',
        pointSpent: 0,
        pointLimit: 5,
        isEnable: false,
        lineNumber: 8,
        rankText: {
            1: "Increases your total Stamina, Intellect, and Spirit by 1%.",
            2: "Increases your total Stamina, Intellect, and Spirit by 2%.",
            3: "Increases your total Stamina, Intellect, and Spirit by 3%.",
            4: "Increases your total Stamina, Intellect, and Spirit by 4%.",
            5: "Increases your total Stamina, Intellect, and Spirit by 5%."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 8,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: "Vampiric Touch",
        src: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_stoicism.jpg',
        pointSpent: 0,
        pointLimit: 1,
        isEnable: false,
        lineNumber: 9,
        rankText: {
            1: "Causes 650 Shadow damage over 15 sec to your target and causes all party members to gain mana equal to 5% of any Shadow spell damage you deal."
        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    },

    {   
        name: undefined,
        src: undefined,
        pointSpent: 0,
        pointLimit: undefined,
        isEnable: false,
        lineNumber: 9,
        rankText: {

        },
        isTalent: false,
        addRequirement: function() { return ""}
        
    }
]